### ISSUE TITLE
Just want to thank you

### ISSUE THREAD

**Issue by jsamr** [amzn/eslint-plugin-no-date-parsing#2]
This plugin has saved a repository from collapse and give us trust that there won't be any date-parsing related regression; thank you so much!

**Comment by joeframbach** [comment]
Thanks for the note. Could you tell me how you found this module to use? It was only recently published and I haven't done anything to publicize it, and it ranks low on Google. Any information you have would help to improve this package's searchability.

**Comment by jsamr** [comment]
I think I searched on google (or DuckDuckGo, can't remember), something along "eslint no date parsing"

**Comment by joeframbach** [comment]
Thanks, have a nice day.

**Comment by jazeee** [comment]
I also found this via Googling for `eslint block date parsing`
Ranks at top.
I also appreciate that this lint package exists!
